apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
    name: bmw-secret
    namespace: bib
spec:
  externalSecretName: bmw-secret
  namespaceSelectors:
  - matchLabels:
      name: bib
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 60m
    secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secret-store
    target:
        name: bmw-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:c14d254c-cb71-48f8-a230-eb380be710f2
          property: BMW_BASE_URL
        secretKey: BMW_BASE_URL
      - remoteRef:
          key: id:c14d254c-cb71-48f8-a230-eb380be710f2
          property: BMW_CLIENT_ID
        secretKey: BMW_CLIENT_ID
      - remoteRef:
          key: id:c14d254c-cb71-48f8-a230-eb380be710f2
          property: BMW_CLIENT_USERNAME
        secretKey: BMW_CLIENT_USERNAME
      - remoteRef:
          key: id:c14d254c-cb71-48f8-a230-eb380be710f2
          property: BMW_CLIENT_PASSWORD
        secretKey: BMW_CLIENT_PASSWORD
      - remoteRef:
          key: id:c14d254c-cb71-48f8-a230-eb380be710f2
          property: BMW_AUTH_URL
        secretKey: BMW_AUTH_URL
      - remoteRef:
          key: id:c14d254c-cb71-48f8-a230-eb380be710f2
          property: BMW_FLEET_ID
        secretKey: BMW_FLEET_ID

