apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: 23a7f246-1ddb-4439-bcab-00d0f9e6a0a7
      accessKey:
        secretRef:
          name: scwsm-sec
          key: access-key
          namespace: bib
      secretKey:
        secretRef:
          name: scwsm-sec
          key: secret-access-key
          namespace: bib

