apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
    name: db-data-ev-secret
    namespace: bib
spec:
  externalSecretName: db-data-ev-secret
  namespaceSelectors:
  - matchLabels:
      name: bib
  - matchLabels:
      name: spark-operator
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 60m
    secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secret-store
    target:
        name: db-data-ev-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_NAME
        secretKey: DB_DATA_EV_NAME
      - remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_HOST
        secretKey: DB_DATA_EV_HOST
      - remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_PORT
        secretKey: DB_DATA_EV_PORT
      - remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_USER
        secretKey: DB_DATA_EV_USER
      - remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_PASSWORD
        secretKey: DB_DATA_EV_PASSWORD

