apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: ev-database-secret
    namespace: bib
spec:
    refreshInterval: 60m
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: ev-database-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:453f52c9-cc8e-4d25-8e61-e83816f52852
          metadataPolicy: None
          property: EV_DATABASE_URL
        secretKey: EV_DATABASE_URL
