apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: secret-results
    namespace: bib
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: secret-results
        creationPolicy: Owner
    data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_NAME
        secretKey: DB_DATA_EV_NAME
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_HOST
        secretKey: DB_DATA_EV_HOST
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_PORT
        secretKey: DB_DATA_EV_PORT
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_USER
        secretKey: DB_DATA_EV_USER
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_PASSWORD
        secretKey: DB_DATA_EV_PASSWORD
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c8be235-5ca0-4e27-b6c3-73f8d38026f4
          metadataPolicy: None
          property: GOOGLE_PRIVATE_KEY
        secretKey: GOOGLE_PRIVATE_KEY
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          metadataPolicy: None
          property: S3_BUCKET
        secretKey: S3_BUCKET
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          metadataPolicy: None
          property: S3_KEY
        secretKey: S3_KEY
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          metadataPolicy: None
          property: S3_SECRET
        secretKey: S3_SECRET
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          metadataPolicy: None
          property: S3_REGION
        secretKey: S3_REGION
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          metadataPolicy: None
          property: S3_ENDPOINT
        secretKey: S3_ENDPOINT
