apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: secret-scraping-soh
    namespace: bib
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: secret-scraping-soh
        creationPolicy: Owner
    data:
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_NAME
        secretKey: DB_DATA_EV_NAME
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_HOST
        secretKey: DB_DATA_EV_HOST
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_PORT
        secretKey: DB_DATA_EV_PORT
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_USER
        secretKey: DB_DATA_EV_USER
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          metadataPolicy: None
          property: DB_DATA_EV_PASSWORD
        secretKey: DB_DATA_EV_PASSWORD
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:6c8be235-5ca0-4e27-b6c3-73f8d38026f4
          metadataPolicy: None
          property: GOOGLE_PRIVATE_KEY
        secretKey: GOOGLE_PRIVATE_KEY
