apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: get-ev-account-secret
  namespace: bib
spec:
  externalSecretName: get-ev-account-secret
  namespaceSelectors:
  - matchLabels:
      name: bib
  - matchLabels:
      name: data-engineering
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 60m
    secretStoreRef:
      kind: ClusterSecretStore
      name: cluster-secret-store
    target:
      name: get-ev-account-secret
      creationPolicy: Owner
    data:
      - remoteRef:
          key: id:bfb58442-25a0-481e-b07e-b28a0d5e0f84
          property: PREMIUM_REPORT_MAIL
        secretKey: PREMIUM_REPORT_MAIL
      - remoteRef:
          key: id:bfb58442-25a0-481e-b07e-b28a0d5e0f84
          property: PREMIUM_REPORT_PWD
        secretKey: PREMIUM_REPORT_PWD
