apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: google-secret
    namespace: bib
spec:
    refreshInterval: 60m
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: google-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:e988fe33-4017-4c86-99a3-5be1516b98cd
          property: GOOGLE_PRIVATE_KEY
        secretKey: GOOGLE_PRIVATE_KEY
      - remoteRef:
          key: id:e988fe33-4017-4c86-99a3-5be1516b98cd
          property: SPREADSHEET_ID
        secretKey: SPREADSHEET_ID
