apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
    name: google-secret
    namespace: bib
spec:
  externalSecretName: google-secret
  namespaceSelectors:
  - matchLabels:
      name: bib
  - matchLabels:
      name: data-engineering
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 60m
    secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secret-store
    target:
        name: google-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:e988fe33-4017-4c86-99a3-5be1516b98cd
          property: GOOGLE_PRIVATE_KEY
        secretKey: GOOGLE_PRIVATE_KEY
      - remoteRef:
          key: id:e988fe33-4017-4c86-99a3-5be1516b98cd
          property: SPREADSHEET_ID
        secretKey: SPREADSHEET_ID

