apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: hm-secret
    namespace: bib
spec:
    refreshInterval: 60m
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: hm-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:739819a9-f2e3-4423-b967-70c7d2aec411
          property: HM_CLIENT_ID
        secretKey: HM_CLIENT_ID
      - remoteRef:
          key: id:739819a9-f2e3-4423-b967-70c7d2aec411
          property: HM_CLIENT_SECRET
        secretKey: HM_CLIENT_SECRET
      - remoteRef:
          key: id:739819a9-f2e3-4423-b967-70c7d2aec411
          property: HM_BASE_URL
        secretKey: HM_BASE_URL

