apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
    name: kia-secret
    namespace: bib
spec:
  externalSecretName: kia-secret
  namespaceSelectors:
  - matchLabels:
      name: bib
  - matchLabels:
      name: data-engineering
  refreshTime: "1h"
  externalSecretSpec:
    refreshInterval: 60m
    secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secret-store
    target:
        name: kia-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: KIA_CLIENT_ID
        secretKey: KIA_CLIENT_ID
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: KIA_AUTH_URL
        secretKey: KIA_AUTH_URL
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: KIA_BASE_URL
        secretKey: KIA_BASE_URL
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: KIA_API_USERNAME
        secretKey: KIA_API_USERNAME
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: KIA_API_PWD
        secretKey: KIA_API_PWD
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: KIA_API_KEY
        secretKey: KIA_API_KEY
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: KIA_PUSH_API_KEY
        secretKey: KIA_PUSH_API_KEY
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: JWT_ALGORITHM
        secretKey: JWT_ALGORITHM
      - remoteRef:
          key: id:da2222a9-fd0b-4b2a-a2f7-0a007b11c0a3
          property: JWT_SECRET
        secretKey: JWT_SECRET

