apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
    name: ms-secret
    namespace: bib
spec:
  externalSecretName: ms-secret
  namespaceSelectors:
  - matchLabels:
      name: bib
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 60m
    secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secret-store
    target:
        name: ms-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:4461caa3-9fba-4216-bae0-755d57b65241
          property: MS_BASE_URL
        secretKey: MS_BASE_URL
      - remoteRef:
          key: id:4461caa3-9fba-4216-bae0-755d57b65241
          property: MS_EMAIL
        secretKey: MS_EMAIL
      - remoteRef:
          key: id:4461caa3-9fba-4216-bae0-755d57b65241
          property: MS_PASSWORD
        secretKey: MS_PASSWORD
      - remoteRef:
          conversionStrategy: Default
          decodingStrategy: None
          key: id:4461caa3-9fba-4216-bae0-755d57b65241
          property: MS_FLEET_ID
        secretKey: MS_FLEET_ID
      - remoteRef:
          key: id:4461caa3-9fba-4216-bae0-755d57b65241
          property: MS_COMPANY
        secretKey: MS_COMPANY

