apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
    name: s3-secret-dev
    namespace: bib
spec:
  externalSecretName: s3-secret-dev
  namespaceSelectors:
  - matchLabels:
      name: bib
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 60m
    secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secret-store
    target:
        name: s3-secret-dev
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:3752928b-0e99-443d-b382-3573b66e6690
          property: S3_BUCKET_DEV
        secretKey: S3_BUCKET_DEV
      - remoteRef:
          key: id:3752928b-0e99-443d-b382-3573b66e6690
          property: S3_KEY_DEV
        secretKey: S3_KEY_DEV
      - remoteRef:
          key: id:3752928b-0e99-443d-b382-3573b66e6690
          property: S3_SECRET_DEV
        secretKey: S3_SECRET_DEV
      - remoteRef:
          key: id:3752928b-0e99-443d-b382-3573b66e6690
          property: S3_ENDPOINT_DEV
        secretKey: S3_ENDPOINT_DEV

