apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
  namespace: bib
spec:
  provider:
    scaleway:
      region: fr-par
      projectId: 23a7f246-1ddb-4439-bcab-00d0f9e6a0a7
      accessKey:
        secretRef:
          name: scwsm-sec
          key: access-key
      secretKey:
        secretRef:
          name: scwsm-sec
          key: secret-access-key
