apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
    name: slack
    namespace: bib
spec:
  externalSecretName: slack
  namespaceSelectors:
  - matchLabels:
      name: bib
  - matchLabels:
      name: data-engineering
  - matchLabels:
      name: dagster
  refreshTime: "1m"
  externalSecretSpec:
    refreshInterval: 60m
    secretStoreRef:
        kind: ClusterSecretStore
        name: cluster-secret-store
    target:
        name: slack-secret
        creationPolicy: Owner
    data:
      - remoteRef:
          key: id:c814efad-77bb-4fca-a867-d750cc904139
          property: OAUTH_TOKEN
        secretKey: OAUTH_TOKEN
      - remoteRef:
          key: id:c814efad-77bb-4fca-a867-d750cc904139
          property: OAUTH_TOKEN
        secretKey: SLACK_TOKEN
