apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: evalue-back-secret
    namespace: evalue
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: evalue-back-secret
        creationPolicy: Owner
    data:
      - secretKey: SECRET_KEY
        remoteRef:
          key: id:7857f051-96fc-405b-b3ea-6725a26c139d
          property: SECRET_KEY
      - secretKey: ENCRYPT_KEY
        remoteRef:
          key: id:7857f051-96fc-405b-b3ea-6725a26c139d
          property: ENCRYPT_KEY
      - secretKey: DB_DATA_EV_HOST
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_HOST
      - secretKey: DB_DATA_EV_PORT
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_PORT
      - secretKey: DB_DATA_EV_NAME
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_NAME
      - secretKey: DB_DATA_EV_USER
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_USER
      - secretKey: DB_DATA_EV_PASSWORD
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_PASSWORD
      - secretKey: S3_BUCKET
        remoteRef:
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          property: S3_BUCKET
      - secretKey: S3_KEY
        remoteRef:
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          property: S3_KEY
      - secretKey: S3_SECRET
        remoteRef:
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          property: S3_SECRET
      - secretKey: S3_ENDPOINT
        remoteRef:
          key: id:b439934f-0748-4a18-bafd-704d99ca70cb
          property: S3_ENDPOINT
      - secretKey: SMTP_EMAIL
        remoteRef:
          key: id:a835d2c6-e952-46ae-9f7f-b3e193788b20
          property: SMTP_EMAIL
      - secretKey: SMTP_USER
        remoteRef:
          key: id:a835d2c6-e952-46ae-9f7f-b3e193788b20
          property: SMTP_USER
      - secretKey: SMTP_PASSWORD
        remoteRef:
          key: id:a835d2c6-e952-46ae-9f7f-b3e193788b20
          property: SMTP_PASSWORD
      - secretKey: SMTP_HOST
        remoteRef:
          key: id:a835d2c6-e952-46ae-9f7f-b3e193788b20
          property: SMTP_HOST
      - secretKey: SMTP_PORT
        remoteRef:
          key: id:a835d2c6-e952-46ae-9f7f-b3e193788b20
          property: SMTP_PORT

