apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evalue-tls
  namespace: evalue
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: evalue-tls
    template:
      type: kubernetes.io/tls
  data:
    # https://dash.cloudflare.com/dd192d9540dadd8d3400f842cf75bc37/get-evalue.com/ssl-tls/origin
    - secretKey: tls.crt
      remoteRef:
        key: id:4275d9ed-5d57-4da8-b268-3af4e8fb1087
    - secretKey: tls.key
      remoteRef:
        key: id:53dffcd4-ad43-4b31-9fb0-550faa763bd5
