apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-api
  namespace: evalue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-api
  template:
    metadata:
      labels:
        app: external-api
    spec:
      containers:
      - name: external-api
        image: rg.fr-par.scw.cloud/evalue/external-api:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "0.5G"
            cpu: "0.5"
          limits:
            memory: "1G"
            cpu: "1"
        envFrom:
        - secretRef:
            name: evalue-back-secret
        - secretRef:
            name: s3-secret
        - secretRef:
            name: db-data-ev-secret
        - secretRef:
            name: db-encryption-secret
        env:
        - name: ALGORITHM
          value: HS256
        - name: COOKIE_DOMAIN
          value: "get-evalue.com"
        - name: FRONTEND_URL
          value: "https://get-evalue.com"
        - name: REDIS_HOST
          value: valkey.data-engineering.svc
        - name: REDIS_PORT
          value: "6379"
        - name: S3_BUCKET
          value: "bib-platform-prod-data"
        - name: S3_BUCKET_ASSETS
          value: "bib-platform-prod-assets"
        - name: SMTP_EMAIL
          value: "flash-report@bib-batteries.fr"
        - name: PREMIUM_REPORT_S3_BUCKET
          value: "bib-premium-reports"
        - name: GOTENBERG_URL
          value: "http://gotenberg.data-engineering.svc:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: external-api
  namespace: evalue
  labels:
    app: external-api
spec:
  selector:
    app: external-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-api-ingress
  namespace: evalue
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/real-ip-header: "CF-Connecting-IP"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - get-evalue.com
    secretName: evalue-tls
  rules:
  - host: get-evalue.com
    http:
      paths:
      - path: /api/v1/
        pathType: Prefix
        backend:
          service:
            name: external-api
            port:
              number: 4000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-api
  namespace: monitoring
  labels:
    app: external-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: external-api
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
  namespaceSelector:
    matchNames:
      - evalue
