apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: evalue-back-secret
    namespace: evalue
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: evalue-back-secret
        creationPolicy: Owner
    data:
      - secretKey: SECRET_KEY
        remoteRef:
          key: id:7857f051-96fc-405b-b3ea-6725a26c139d
          property: SECRET_KEY
          version: latest_enabled
      - secretKey: ENCRYPT_KEY
        remoteRef:
          key: id:7857f051-96fc-405b-b3ea-6725a26c139d
          property: ENCRYPT_KEY
          version: latest_enabled
      - secretKey: DB_DATA_EV_HOST
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_HOST
          version: latest_enabled
      - secretKey: DB_DATA_EV_PORT
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_PORT
          version: latest_enabled
      - secretKey: DB_DATA_EV_NAME
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_NAME
          version: latest_enabled
      - secretKey: DB_DATA_EV_USER
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_USER
          version: latest_enabled
      - secretKey: DB_DATA_EV_PASSWORD
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_PASSWORD
          version: latest_enabled

