apiVersion: apps/v1
kind: Deployment
metadata:
  name: evalue-front
  namespace: evalue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evalue-front
  template:
    metadata:
      labels:
        app: evalue-front
    spec:
      containers:
      - name: evalue-front
        image: rg.fr-par.scw.cloud/evalue/evalue-front:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "0.5G"
            cpu: "0.5"
          limits:
            memory: "1G"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: evalue-front
  namespace: evalue
spec:
  selector:
    app: evalue-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evalue-front-redirect
  namespace: evalue
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://app.bib-batteries.com
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - get-evalue.com
    secretName: evalue-tls
  rules:
  - host: get-evalue.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: evalue-front
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evalue-front-ingress
  namespace: evalue
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/real-ip-header: "CF-Connecting-IP"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.bib-batteries.com
    secretName: app-bib-batteries-tls
  rules:
  - host: app.bib-batteries.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: evalue-front
            port:
              number: 3000
