apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: evalue-back-secret
    namespace: evalue
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: evalue-back-secret
        creationPolicy: Owner
    data:
      - secretKey: SECRET_KEY
        remoteRef:
          key: id:7857f051-96fc-405b-b3ea-6725a26c139d
          property: SECRET_KEY
      - secretKey: ENCRYPT_KEY
        remoteRef:
          key: id:7857f051-96fc-405b-b3ea-6725a26c139d
          property: ENCRYPT_KEY
      - secretKey: DB_DATA_EV_HOST
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_HOST
      - secretKey: DB_DATA_EV_PORT
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_PORT
      - secretKey: DB_DATA_EV_NAME
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_NAME
      - secretKey: DB_DATA_EV_USER
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_USER
      - secretKey: DB_DATA_EV_PASSWORD
        remoteRef:
          key: id:6c1d6fa8-e7e2-4a10-aa3e-1be97e523c60
          property: DB_DATA_EV_PASSWORD
      - secretKey: TESLA_CLIENT_ID
        remoteRef:
          key: id:b10fb5a4-5e5f-4637-ae51-337b72d0c628
          property: CLIENT_ID
      - secretKey: TESLA_CLIENT_SECRET
        remoteRef:
          key: id:b10fb5a4-5e5f-4637-ae51-337b72d0c628
          property: CLIENT_SECRET
