apiVersion: apps/v1
kind: Deployment
metadata:
  name: evalue-front
  namespace: evalue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evalue-front
  template:
    metadata:
      labels:
        app: evalue-front
    spec:
      containers:
      - name: evalue-front
        image: rg.fr-par.scw.cloud/bib-images/evalue-front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 500M
            cpu: 500m
          limits:
            memory: 2G
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: evalue-front
  namespace: evalue
spec:
  selector:
    app: evalue-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evalue-front-ingress
  namespace: evalue
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - get-evalue.com
    secretName: evalue-front-tls
  rules:
  - host: get-evalue.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: evalue-front
            port:
              number: 3000

