apiVersion: batch/v1
kind: Job
metadata:
  name: results-job
  namespace: bib
spec:
  template:
    metadata:
      labels:
        app: results-job
    spec:
      restartPolicy: Never
      containers:
        - name: results
          image: rg.fr-par.scw.cloud/bib-images/results:latest
          imagePullPolicy: Always
          command: ["python", "src/results/main.py"]
          envFrom:
            - secretRef:
                name: secret-results
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "1"

