apiVersion: batch/v1
kind: Job
metadata:
  name: scraping-soh-job
  namespace: bib
spec:
  template:
    metadata:
      labels:
        app: scraping-soh
    spec:
      restartPolicy: Never
      containers:
        - name: scraping-soh
          image: rg.fr-par.scw.cloud/bib-images/scraping_soh:latest
          imagePullPolicy: Always
          command: ["python", "src/ingestion/soh_scraping/main.py"]
          args: ["spoticar", "autospherre", "aramis", "ev_market"]
          envFrom:
            - secretRef:
                name: secret-scraping-soh
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "1"

