apiVersion: batch/v1
kind: CronJob
metadata:
  name: act-activating-vehicles
  namespace: data-engineering
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: act-activating-vehicles
        spec:
          restartPolicy: Never
          containers:
            - name: act-activating-vehicles-1
              image: rg.fr-par.scw.cloud/data-engineering/activation:latest
              imagePullPolicy: Always
              command: ["python", "src/activation/main.py"]
              envFrom:
                - secretRef:
                    name: db-data-ev-secret
                - secretRef:
                    name: google-secret
                - secretRef:
                    name: vw-secret
                - secretRef:
                    name: bmw-secret
                - secretRef:
                    name: ms-secret
                - secretRef:
                    name: renault-secret
                - secretRef:
                    name: hm-secret
                - secretRef:
                    name: tesla-secret
                - secretRef:
                    name: kia-secret
                - secretRef:
                    name: slack-secret
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "1"
                requests:
                  memory: "2Gi"
                  cpu: "1"

