apiVersion: batch/v1
kind: CronJob
metadata:
  name: act-activating-vehicles
  namespace: data-engineering
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: act-activating-vehicles
        spec:
          restartPolicy: Never
          containers:
            - name: act-activating-vehicles-1
              image: rg.fr-par.scw.cloud/data-engineering/activation:latest
              imagePullPolicy: Always
              command: ["python", "src/activation/main.py"]
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
              envFrom:
                - secretRef:
                    name: s3-secret
                - secretRef:
                    name: db-data-ev-secret
                - secretRef:
                    name: google-secret
                - secretRef:
                    name: vw-secret
                - secretRef:
                    name: bmw-secret
                - secretRef:
                    name: ms-secret
                - secretRef:
                    name: renault-secret
                - secretRef:
                    name: hm-secret
                - secretRef:
                    name: tesla-secret
                - secretRef:
                    name: kia-secret
                - secretRef:
                    name: slack-secret
                - secretRef:
                    name: db-data-eng-secret
                - secretRef:
                    name: db-encryption-secret
              env:
                - name: S3_BUCKET
                  value: "bib-platform-prod-data"
                - name: METRIC_SLACK_CHANNEL_ID
                  value: "C09RUV9T2UR"
                - name: TESLA_VEHICLE_COMMAND_CERT_PATH
                  value: /secrets/tesla-vehicle-command/vehicle-command-tls-cert.pem
                - name: TESLA_VEHICLE_COMMAND_KEY_PATH
                  value: /secrets/tesla-vehicle-command/vehicle-command-tls-key.pem
                - name: FLEET_TELEMETRY_CERT_PATH
                  value: /secrets/fleet-telemetry-tls/tls.crt
                - name: FLEET_TELEMETRY_KEY_PATH
                  value: /secrets/fleet-telemetry-tls/tls.key
                - name: METRIC_CHANNEL_ID
                  value: "C09RUV9T2U"
                - name: TESLA_VEHICLE_COMMAND_SERVICE_URL
                  value: "https://tesla-vehicle-command.data-engineering.svc:4443"
                - name: FLEET_TELEMETRY_HOSTNAME
                  value: "fleet-telemetry.bib-data.fr"
              volumeMounts:
                - name: tesla-vehicle-command-secret
                  mountPath: /secrets/tesla-vehicle-command
                  readOnly: true
                - name: fleet-telemetry-tls
                  mountPath: /secrets/fleet-telemetry-tls
                  readOnly: true
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "1"
                requests:
                  memory: "2Gi"
                  cpu: "1"
          volumes:
            - name: tesla-vehicle-command-secret
              secret:
                secretName: tesla-vehicle-command-secret
            - name: fleet-telemetry-tls
              secret:
                secretName: fleet-telemetry.bib-data.fr-tls
