apiVersion: batch/v1
kind: CronJob
metadata:
  name: com-compressing-stellantis
  namespace: bib
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: com-compressing-stellantis
        spec:
          restartPolicy: Never
          containers:
            - name: com-compressing-stellantis-1
              image: rg.fr-par.scw.cloud/bib-images/data_ev:latest
              imagePullPolicy: Always
              command: ["python", "-m",  "src.transform.compressor.main"]
              args: ["stellantis"]
              envFrom:
                - secretRef:
                    name: s3-secret
                - secretRef:
                    name: s3-secret-dev
              env:
                - name: S3_BUCKET
                  value: "bib-platform-prod-data"
                - name: S3_BUCKET_DEV
                  value: "bib-platform-dev-data"
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "1"
                requests:
                  memory: "2Gi"
                  cpu: "1"

