apiVersion: batch/v1
kind: CronJob
metadata:
  name: ing-fetching-ev-database
  namespace: data-engineering
spec:
  schedule: "0 8 * * 1"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ing-fetching-ev-database
        spec:
          restartPolicy: Never
          containers:
            - name: ing-fetching-ev-database-1
              image: rg.fr-par.scw.cloud/data-engineering/ev_database:latest
              imagePullPolicy: Always
              command: ["python", "src/ingestion/ev_database/ev_database.py"]
              envFrom:
                - secretRef:
                    name: db-data-ev-secret
                - secretRef:
                    name: ev-database-secret
              env:
                - name: S3_BUCKET
                  value: "bib-platform-prod-data"
                - name: S3_BUCKET_DEV
                  value: "bib-platform-dev-data"
              resources:
                limits:
                  memory: "2Gi"
                  cpu: "1"
                requests:
                  memory: "2Gi"
                  cpu: "1"

