apiVersion: batch/v1
kind: CronJob
metadata:
  name: ing-scraping-marketplaces
  namespace: data-engineering
spec:
  schedule: "0 8 * * 1"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ing-scraping-marketplaces
        spec:
          restartPolicy: Never
          containers:
            - name: ing-scraping-marketplaces-1
              image: rg.fr-par.scw.cloud/data-engineering/scraping_soh:latest
              imagePullPolicy: Always
              command: ["python", "src/ingestion/soh_scraping/main.py"]
              args: ["spoticar", "autospherre", "aramis", "ev_market"]
              envFrom:
                - secretRef:
                    name: db-data-ev-secret
                - secretRef:
                    name: s3-secret
                - secretRef:
                    name: google-secret
              env:
                - name: S3_BUCKET
                  value: "bib-platform-prod-data"
                - name: S3_BUCKET_DEV
                  value: "bib-platform-dev-data"
              resources:
                limits:
                  memory: "4Gi"
                  cpu: "2"
                requests:
                  memory: "2Gi"
                  cpu: "1"

