apiVersion: batch/v1
kind: Job
metadata:
  name: enr-adding-results
  namespace: data-engineering
spec:
  template:
    metadata:
      labels:
        app: results-job
    spec:
      restartPolicy: Never
      containers:
        - name: results
          image: rg.fr-par.scw.cloud/data-engineering/results:latest
          imagePullPolicy: Always
          command: ["python", "src/results/main.py"]
          envFrom:
            - secretRef:
                name: s3-secret
            - secretRef:
                name: db-data-ev-secret
            - secretRef:
                name: google-secret
          env:
            - name: S3_BUCKET
              value: "bib-platform-prod-data"
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "1"

