apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-ms
  namespace: data-engineering
  labels:
    app: ingestion-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-ms
  template:
    metadata:
      labels:
        app: ingestion-ms
    spec:
      containers:
        - name: ingestion-ms
          image: rg.fr-par.scw.cloud/data-engineering/ms-ingestion:latest
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: ms-secret
            - secretRef:
                name: s3-secret
          env:
            # Redis Configuration
            - name: REDIS_HOST
              value: valkey.data-engineering.svc
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB_INGESTION
              value: "1"
            - name: REDIS_DB_KAFKA_CACHE
              value: "2"
            # S3 Configuration
            - name: S3_BUCKET
              value: "bib-platform-prod-data"
            # Kafka Configuration
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "bib-kafka-bootstrap.kafka.svc:9092"
            - name: KAFKA_PUSH_TOPIC
              value: "oem_push_data"
