apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-hm
  namespace: data-engineering
  labels:
    app: ingestion-hm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-hm
  template:
    metadata:
      labels:
        app: ingestion-hm
    spec:
      containers:
        - name: ingestion-hm
          image: rg.fr-par.scw.cloud/data-engineering/hm-ingestion:latest
          imagePullPolicy: Always
          command: ["python", "src/ingestion/high_mobility/__main__.py", "--max_workers", "8"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
          envFrom:
            - secretRef:
                name: hm-secret
            - secretRef:
                name: s3-secret
          env:
            - name: REDIS_HOST
              value: valkey.data-engineering.svc
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB_INGESTION
              value: "1"
            - name: S3_BUCKET
              value: "bib-platform-prod-data"

