apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      containers:
        - name: spark-history-server
          image: rg.fr-par.scw.cloud/data-engineering/spark:1
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          args: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer"]
          ports:
            - containerPort: 18080
          env:
          - name: SPARK_HISTORY_OPTS
            value: |
              -Dspark.history.fs.logDirectory=s3a://bib-prod-spark-history/spark-events
              -Dspark.hadoop.fs.s3a.endpoint=s3.fr-par.scw.cloud
              -Dspark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
              -Dspark.hadoop.fs.s3a.path.style.access=true
              -Dspark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: S3_KEY
                name: s3-secret
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: S3_SECRET
                name: s3-secret
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1.5"
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server-service
  namespace: spark-operator
spec:
  type: ClusterIP
  selector:
    app: spark-history-server
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/auth-signin: https://auth.bibers.fr/oauth2/start?rd=$scheme://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://auth.bibers.fr/oauth2/auth
  name: spark-history-server-ingress
  namespace: spark-operator
spec:
  ingressClassName: nginx
  rules:
  - host: spark-history.bibers.fr
    http:
      paths:
      - backend:
          service:
            name: spark-history-server-service
            port:
              number: 18080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - spark-history.bibers.fr
    secretName: spark-history-server-tls
