# --- Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: data-engineering
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: rg.fr-par.scw.cloud/data-engineering/data-catalog:latest
          envFrom:
            - secretRef:
                name: db-data-ev-secret
            - secretRef:
                name: google-secret
            - secretRef:
                name: db-data-eng-secret
            - secretRef:
                name: s3-secret
          ports:
            - containerPort: 8501
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
            requests:
              memory: "256Mi"
              cpu: "100m"

---
# --- Service ---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: data-engineering
spec:
  type: ClusterIP
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-ingress
  namespace: data-engineering
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: internal-service-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Protected Streamlit"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - data-catalog.prod.bibers.fr
      secretName: data-catalog-tls
  rules:
    - host: data-catalog.prod.bibers.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: streamlit-service
                port:
                  number: 8501

